# NumPy Practices

In [2]:
import numpy as np

## Create a NumPy array

In [9]:
# matlab: [ 1 2 3; 4 5 6 ]  -> float?

# create np.int64: 2**64 = 1.8446744e+19 
 
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [16]:
print(f"Type: {type(x)}")
print(f"Data Type: {x.dtype}") # datatype
print(f"Number of dimension: {x.ndim}") # number of dimension
print(f"Number of elements: {x.size}") # number of elements
print(f"Dimension: {x.shape}") # Dimension

Type: <class 'numpy.ndarray'>
Data Type: int64
Number of dimension: 2
Number of elements: 6
Dimension: (2, 3)


In [19]:
# not always 2 dim mension
x1 = np.array([1, 2, 3])
x2 = np.array([[1, 2, 3]])

print(f"x1 ndim = {x1.ndim} | {x1.shape}")  # (3, ) is tuple, (3) equals 3, int
print(f"x1 ndim = {x2.ndim} | {x2.shape}")

x1 ndim = 1 | (3,)
x1 ndim = 2 | (1, 3)


In [39]:
# create other type tensor
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
x

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### often used methods

In [24]:
# = range
np.arange(0, 9, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# linspace
np.linspace(1, 5, 9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [31]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# ones matrix
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [36]:
# zeros matrix
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [45]:
# get dialog matrix elem
np.diag(x, 2)

array([3.], dtype=float32)

In [77]:
# create random numpy array
# random samples from a uniform distribution: Uniform [0, 1)
np.random.rand(3, 5)

array([[0.38656803, 0.3171012 , 0.05712714, 0.0089144 , 0.28984494],
       [0.12406282, 0.2338381 , 0.89610451, 0.13549445, 0.40979219],
       [0.15671899, 0.4167    , 0.46405575, 0.42624289, 0.56451287]])

In [78]:
# create random numpy array
# random samples from a normal distribution: Gaussian (mean=0, std=1)
np.random.randn(3, 5)

array([[-1.10642359, -0.11137323,  1.28787433, -0.09711504, -0.68655805],
       [ 0.27990781,  1.66678672,  0.11378623,  1.20713174,  0.03440031],
       [-0.49653675,  0.94879641,  1.01591378, -2.0413474 ,  0.10078489]])

In [80]:
# create random numpy array
# random samples from a normal distribution: Gaussian (mean=0, std=1)
np.random.randint(0, 9, size=(5,), dtype=np.int64)

array([5, 6, 6, 5, 6])

In [169]:
# random choice
x = np.arange(0, 10)
np.random.choice(x, size=(4,), replace=False)

array([7, 2, 9, 3])

In [175]:
np.random.seed(777)
# fix seed to create constant result
np.random.randint(0, 9, size=(5,), dtype=np.int64)

array([7, 6, 7, 1, 7])

## Access elements

In [108]:
# reshape
x = np.arange(0, 15)  # 0, 1, ..., 14  | size(numel) = 15
print(x)
print()
print("x.reshape(5, 3)")  
print(x.reshape(5, 3))
print()
print("x.reshape(5, -1)")
print(x.reshape(5, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

x.reshape(5, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

x.reshape(5, -1)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [57]:
# reshape
x = np.arange(0, 15).reshape(5, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

```
          0   1   2
   0   [[ 0,  1,  2],
   1    [ 3,  4,  5],
   2    [ 6,  7,  8],
   3    [ 9, 10, 11],
   4    [12, 13, 14]])
```

In [60]:
# select single element
x[0, 1]  # scalar(integer)

1

In [62]:
# select first row
x[0, :]  # ndim = 1

array([0, 1, 2])

In [63]:
# select second column
x[:, 1]  # ndim = 1

array([ 1,  4,  7, 10, 13])

In [59]:
# select row: 0~2, colulm: 1
x[0:2, 1:2]

array([[1],
       [4]])

In [66]:
# select even index row, column
x[0:5:2, 0:3:2]   # equals to x[::2, ::2]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

In [71]:
# filp
x[::-1, :]

array([[12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [75]:
# differrence between ndim=1, ndim=2
x1 = np.array([1, 2, 3])   # shape = (3, )
x2 = np.array([[1, 2, 3]])  # shape = (1, 3)

print(f"Select index 0 from x1: {x1[0]}")
print(f"Select index 0 from x2: {x2[0]}")

print(f"Select index 1 from x1: {x1[1]}")
print(f"Select index 1 from x2: {x2[1]}")

Select index 0 from x1: 1
Select index 0 from x2: [1 2 3]
Select index 1 from x1: 2


IndexError: index 1 is out of bounds for axis 0 with size 1

In [76]:
print(f"Select index 1 from x2: {x2[0, 1]}")

Select index 1 from x2: 2


## Operations

In [186]:
x = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])
x.shape

(2, 4)

In [195]:
# relation operation, returns boolean array
x == 1

array([[ True, False, False, False],
       [False, False, False, False]])

In [190]:
# can use it to select array
x[x == 1]

array([1])

In [96]:
# summation
print(x)
print(f"Sum all elements: {x.sum()}")
print()
print("np.sum(x, axis=0): ")
print(np.sum(x, axis=0))  # same as x.sum(0)
print()
print("np.sum(x, axis=1): ")
print(np.sum(x, axis=1))  # same as x.sum(1)

[[1 2 3 4]
 [5 6 7 8]]
Sum all elements: 36

np.sum(x, axis=0): 
[ 6  8 10 12]

np.sum(x, axis=1): 
[10 26]


In [97]:
# mean
print(x)
print(f"Mean all elements: {x.mean()}")
print()
print("np.mean(x, axis=0): ")
print(np.mean(x, axis=0))  # same as x.mean(0)
print()
print("np.mean(x, axis=1): ")
print(np.mean(x, axis=1))  # same as x.mean(1)

[[1 2 3 4]
 [5 6 7 8]]
Mean all elements: 4.5

np.mean(x, axis=0): 
[3. 4. 5. 6.]

np.mean(x, axis=1): 
[2.5 6.5]
Mean all elements: 4.5


max, min is also same as sum, mean

In [98]:
# transpose
x = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])

x.T  # x.shape = (4, 2)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [99]:
# flatten
x.flatten()  # x.ndim = 1

array([1, 2, 3, 4, 5, 6, 7, 8])

### element-wise product

In [158]:
x = np.array([[1], [2], [3]])
x * x

array([[1],
       [4],
       [9]])

broad casting: http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html

In [161]:
x * 3

array([[3],
       [6],
       [9]])

### dot product
`help(np.dot)`

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
  and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of `b`::


In [130]:
# 1. a and b are both 1-D array  -> inner product
a = np.array([1, 2, 3])  # shape: (3,)
b = np.array([4, 5, 6])  # shape: (3,)

print("np.dot(a, b) = 1*4 + 2*5 + 3*6")
np.dot(a, b)

np.dot(a, b) = 1x4 + 2x5 + 3x6


32

In [134]:
# 2. a and b are both 2-D array -> matrix multiplication
a = np.array([[1, 2, 3]])  # shape: (1, 3)
b = np.array([[4, 5],
              [6, 7],
              [8, 9]])  # shape: (3, 2)

print("np.dot(a, b) -> shape = (1, 3) x (3, 2) = (1, 2)")
np.dot(a, b)  # same as: a @ b, np.matmul(a, b)

np.dot(a, b)


array([[40, 46]])

In [151]:
# 3. a is an N-D array and b is a 1-D array,
# it is a sum product over the last axis of a and b
a = np.array([[[1, 2], 
               [3, 4], 
               [5, 6]]])  # shape: (1, 3, 2)
b = np.array([1, 2])  # shape: (2,)

print("np.dot(a, b) -> shape = (1, 3, 2) x (2,) = (1, 3)")
# first element: 1*1 + 2*2 
# second element: 3*1 + 4*2 
# third element: 5*1 + 6*2
np.dot(a, b)

np.dot(a, b) -> shape = (1, 3, 2) x (2,) = (1, 3)


array([[ 5, 11, 17]])

In [162]:
# If a is an N-D array and b is an M-D array (where M>=2), 
# it is a sum product over the last axis of a and the second-to-last axis of b::
a = np.array([[[1, 2], 
               [3, 4], 
               [5, 6]]])  # shape: (1, 3, 2)
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # shape: (2, 4)

print("np.dot(a, b) -> shape = (1, 3, 2) x (2, 4) = (1, 3, 4)")
np.dot(a, b)

np.dot(a, b) -> shape = (1, 3, 2) x (2, 4) = (1, 3, 4)


array([[[11, 14, 17, 20],
        [23, 30, 37, 44],
        [35, 46, 57, 68]]])

## merge arrays

In [119]:
# concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.concatenate([a, b])")
print(f"{np.concatenate([a, b])}")  # ndim = 1
print(f"{np.concatenate([a, b], axis=0)}")  # ndim = 1

np.concatenate([a, b])
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [120]:
print("Must reshape to 2 ndim array to concatenate by axis=0")
print("method 1: reshape")
print(f"{np.concatenate([a.reshape(1, 3), b.reshape(1, 3)], axis=0)}")
print("method 2: np.newaxis")
print(f"{np.concatenate([a[np.newaxis, :], b[np.newaxis, :]], axis=0)}")

Must reshape to 2 ndim array to concatenate by axis=0
method 1: reshape
[[1 2 3]
 [4 5 6]]
method 2: np.newaxis
[[1 2 3]
 [4 5 6]]


In [123]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])